-- ============================================================================
-- PROJECT XP - MODÉRATION MONDIALE V2
--
-- IMPORTANT :
-- N'exécute ce script qu'APRÈS :
--   1. avoir déployé l'Edge Function "send-moderated-message" ;
--   2. avoir ajouté le secret OPENAI_API_KEY ;
--   3. avoir installé les nouveaux fichiers Flutter ;
--   4. avoir testé un envoi normal.
--
-- Le script retire ensuite l'INSERT direct aux applications clientes afin que
-- la modération serveur ne puisse pas être contournée avec une APK modifiée.
-- ============================================================================


-- ============================================================================
-- JOURNAL DE MODÉRATION SANS STOCKER LE TEXTE BRUT
-- ============================================================================

create table if not exists public.moderation_events (
  id bigint generated by default as identity primary key,

  user_id uuid
    references auth.users(id)
    on delete set null,

  surface text not null,

  decision text not null,

  categories text[] not null
    default '{}'::text[],

  content_sha256 text,

  created_at timestamptz not null
    default now(),

  constraint moderation_events_surface_check
    check (
      surface in (
        'tavern',
        'private'
      )
    ),

  constraint moderation_events_decision_check
    check (
      decision in (
        'blocked',
        'safety_signal'
      )
    )
);


alter table public.moderation_events
enable row level security;


-- Aucun accès client direct.
revoke all
on public.moderation_events
from anon,
     authenticated;


-- ============================================================================
-- EMPÊCHER LE CONTOURNEMENT DE LA MODÉRATION CONTEXTUELLE
--
-- Les lectures Realtime restent inchangées.
-- Les mises à jour nécessaires (ex: read_at via RPC) restent inchangées.
-- On retire uniquement INSERT aux clients.
--
-- L'Edge Function utilise le rôle serveur et peut continuer à insérer.
-- ============================================================================

revoke insert
on public.tavern_messages
from anon,
     authenticated;


revoke insert
on public.private_messages
from anon,
     authenticated;


-- ============================================================================
-- FIN
-- ============================================================================
