-- ============================================================================
-- PROJECT XP - MODÉRATION "HARD BLOCK" V1
--
-- Objectifs :
--   1. Stocker une liste administrable de termes réellement problématiques.
--   2. Bloquer les messages Taverne ET les messages privés côté serveur.
--   3. Résister aux contournements simples :
--      accents, 0/o, 1/i, 3/e, 4/a, 5/s, 7/t, @/a,
--      ponctuation et séparateurs artificiels.
--
-- Les jurons ordinaires ne sont volontairement PAS bloqués.
-- ============================================================================


-- ============================================================================
-- EXTENSION POUR LA NORMALISATION DES ACCENTS
-- ============================================================================

create extension if not exists unaccent
with schema extensions;


-- ============================================================================
-- TABLE DES TERMES BLOQUÉS
-- ============================================================================

create table if not exists public.moderation_blocked_terms (
  id bigint generated by default as identity primary key,

  term text not null unique,

  category text not null
    default 'identity_slur',

  compact_match boolean not null
    default false,

  active boolean not null
    default true,

  created_at timestamptz not null
    default now()
);


-- ============================================================================
-- SÉCURITÉ RLS
-- ============================================================================

alter table public.moderation_blocked_terms
enable row level security;


drop policy if exists
  "authenticated_can_read_active_moderation_terms"
on public.moderation_blocked_terms;


create policy
  "authenticated_can_read_active_moderation_terms"
on public.moderation_blocked_terms
for select
to authenticated
using (
  active = true
);


-- Permet à l'application Project XP de lire la liste active.
-- Les modifications restent interdites aux utilisateurs ordinaires.

grant select
on public.moderation_blocked_terms
to authenticated;


-- ============================================================================
-- LISTE INITIALE
--
-- Liste volontairement courte et sévère afin d'éviter un maximum de
-- faux positifs.
--
-- Elle pourra ensuite être modifiée directement dans Supabase sans
-- republier l'application.
-- ============================================================================

insert into public.moderation_blocked_terms (
  term,
  category,
  compact_match,
  active
)
values
  (
    'bougnoule',
    'identity_slur',
    true,
    true
  ),
  (
    'bicot',
    'identity_slur',
    true,
    true
  ),
  (
    'youpin',
    'identity_slur',
    true,
    true
  ),
  (
    'chinetoque',
    'identity_slur',
    true,
    true
  ),
  (
    'nègre',
    'identity_slur',
    true,
    true
  ),
  (
    'sale arabe',
    'identity_slur',
    true,
    true
  ),
  (
    'sale juif',
    'identity_slur',
    true,
    true
  ),
  (
    'sale noir',
    'identity_slur',
    true,
    true
  ),
  (
    'sale asiatique',
    'identity_slur',
    true,
    true
  ),
  (
    'pédé',
    'identity_slur',
    false,
    true
  ),
  (
    'pd',
    'identity_slur',
    false,
    true
  ),
  (
    'salope',
    'identity_slur',
    false,
    true
  ),
  (
    'pute',
    'identity_slur',
    false,
    true
  ),
  (
    'gouine',
    'identity_slur',
    true,
    true
  ),
  (
    'nigger',
    'identity_slur',
    true,
    true
  ),
  (
    'nigga',
    'identity_slur',
    true,
    true
  ),
  (
    'faggot',
    'identity_slur',
    true,
    true
  ),
  (
    'kike',
    'identity_slur',
    false,
    true
  ),
  (
    'chink',
    'identity_slur',
    true,
    true
  ),
  (
    'spic',
    'identity_slur',
    false,
    true
  ),
  (
    'wetback',
    'identity_slur',
    true,
    true
  ),
  (
    'tranny',
    'identity_slur',
    true,
    true
  ),
  (
    'raghead',
    'identity_slur',
    true,
    true
  )

on conflict (term)
do update
set
  category =
    excluded.category,

  compact_match =
    excluded.compact_match,

  active =
    excluded.active;


-- ============================================================================
-- NORMALISATION DU TEXTE
--
-- Exemple :
--
--   "N.I.G.G.E.R"
--       ↓
--   "n i g g e r"
--
--   "n1gg3r"
--       ↓
--   "nigger"
--
--   "NÈGRE"
--       ↓
--   "negre"
--
-- ============================================================================

create or replace function public.project_xp_moderation_normalize(
  p_text text
)
returns text

language plpgsql

stable

set search_path =
  public,
  extensions

as $$

declare

  v_text text;

begin

  v_text :=
    lower(
      unaccent(
        coalesce(
          p_text,
          ''
        )
      )
    );


  -- --------------------------------------------------------------------------
  -- SUBSTITUTIONS SIMPLES DE TYPE "LEETSPEAK"
  -- --------------------------------------------------------------------------

  v_text :=
    replace(
      v_text,
      '0',
      'o'
    );

  v_text :=
    replace(
      v_text,
      '1',
      'i'
    );

  v_text :=
    replace(
      v_text,
      '3',
      'e'
    );

  v_text :=
    replace(
      v_text,
      '4',
      'a'
    );

  v_text :=
    replace(
      v_text,
      '5',
      's'
    );

  v_text :=
    replace(
      v_text,
      '7',
      't'
    );

  v_text :=
    replace(
      v_text,
      '@',
      'a'
    );

  v_text :=
    replace(
      v_text,
      '$',
      's'
    );

  v_text :=
    replace(
      v_text,
      '€',
      'e'
    );


  -- --------------------------------------------------------------------------
  -- PONCTUATION / CARACTÈRES SPÉCIAUX → ESPACES
  -- --------------------------------------------------------------------------

  v_text :=
    regexp_replace(
      v_text,
      '[^a-z0-9]+',
      ' ',
      'g'
    );


  -- --------------------------------------------------------------------------
  -- ESPACES MULTIPLES → UN SEUL ESPACE
  -- --------------------------------------------------------------------------

  v_text :=
    regexp_replace(
      v_text,
      '\s+',
      ' ',
      'g'
    );


  return btrim(
    v_text
  );

end;

$$;


-- ============================================================================
-- CONTRÔLE CENTRAL D'UN MESSAGE
-- ============================================================================

create or replace function public.project_xp_assert_message_allowed(
  p_content text
)
returns void

language plpgsql

security definer

set search_path =
  public,
  extensions

as $$

declare

  v_text text;

  v_compact_text text;

  v_term text;

  v_compact_term text;

  v_blocked record;

begin

  v_text :=
    public.project_xp_moderation_normalize(
      p_content
    );


  if v_text = '' then
    return;
  end if;


  -- Version sans espaces.
  --
  -- Exemple :
  --
  -- n i g g e r
  -- ↓
  -- nigger

  v_compact_text :=
    replace(
      v_text,
      ' ',
      ''
    );


  for v_blocked in

    select
      term,
      compact_match

    from
      public.moderation_blocked_terms

    where
      active = true

  loop

    v_term :=
      public.project_xp_moderation_normalize(
        v_blocked.term
      );


    if v_term = '' then
      continue;
    end if;


    -- ========================================================================
    -- MOT OU EXPRESSION COMPLÈTE
    -- ========================================================================

    if position(
      ' ' || v_term || ' '

      in

      ' ' || v_text || ' '
    ) > 0 then

      raise exception
        'PROJECT_XP_CONTENT_BLOCKED'

        using errcode =
          'P0001';

    end if;


    -- ========================================================================
    -- VARIANTE AVEC ESPACES / PONCTUATION ARTIFICIELS
    -- ========================================================================

    if v_blocked.compact_match then

      v_compact_term :=
        replace(
          v_term,
          ' ',
          ''
        );


      -- On évite cette recherche agressive sur les termes très courts
      -- afin de réduire les faux positifs.

      if char_length(
           v_compact_term
         ) >= 5

         and position(
           v_compact_term

           in

           v_compact_text
         ) > 0 then

        raise exception
          'PROJECT_XP_CONTENT_BLOCKED'

          using errcode =
            'P0001';

      end if;

    end if;

  end loop;

end;

$$;


-- ============================================================================
-- PROTECTION DE LA TAVERNE
-- ============================================================================

create or replace function public.project_xp_moderate_tavern_message()
returns trigger

language plpgsql

security definer

set search_path =
  public,
  extensions

as $$

begin

  perform
    public.project_xp_assert_message_allowed(
      new.content
    );


  return new;

end;

$$;


drop trigger if exists
  trg_project_xp_moderate_tavern_message

on public.tavern_messages;


create trigger
  trg_project_xp_moderate_tavern_message

before insert
or update of content

on public.tavern_messages

for each row

execute function
  public.project_xp_moderate_tavern_message();


-- ============================================================================
-- PROTECTION DES MESSAGES PRIVÉS
-- ============================================================================

create or replace function public.project_xp_moderate_private_message()
returns trigger

language plpgsql

security definer

set search_path =
  public,
  extensions

as $$

begin

  perform
    public.project_xp_assert_message_allowed(
      new.content
    );


  return new;

end;

$$;


drop trigger if exists
  trg_project_xp_moderate_private_message

on public.private_messages;


create trigger
  trg_project_xp_moderate_private_message

before insert
or update of content

on public.private_messages

for each row

execute function
  public.project_xp_moderate_private_message();


-- ============================================================================
-- FIN — PROJECT XP MODÉRATION HARD BLOCK V1
-- ============================================================================