-- ============================================================================
-- PROJECT XP - MODÉRATION V2.2
-- LEXIQUE MONDIAL + INDEXATION LÉGÈRE
--
-- À exécuter AVANT d'importer le lexique mondial.
--
-- Cette migration :
--   1. crée le stockage du lexique mondial ;
--   2. garde les termes clients privés (service_role uniquement) ;
--   3. crée un RPC rapide de correspondance par candidats ;
--   4. crée le journal de modération s'il n'existe pas encore ;
--   5. NE verrouille PAS encore les INSERT des messages.
--
-- La liste V1 public.moderation_blocked_terms reste active et continue
-- d'assurer le hard-block des termes critiques déjà validés.
-- ============================================================================


-- ============================================================================
-- SOURCE DU LEXIQUE
-- ============================================================================

create table if not exists public.moderation_lexicon_sources (
  source_key text primary key,

  display_name text not null,

  source_url text not null,

  license_name text not null,

  source_revision text not null
    default 'main',

  import_enabled boolean not null
    default true,

  imported_at timestamptz,

  term_count integer not null
    default 0,

  language_count integer not null
    default 0,

  created_at timestamptz not null
    default now(),

  updated_at timestamptz not null
    default now()
);


alter table public.moderation_lexicon_sources
enable row level security;


revoke all
on public.moderation_lexicon_sources
from anon,
     authenticated;


insert into public.moderation_lexicon_sources (
  source_key,
  display_name,
  source_url,
  license_name,
  source_revision,
  import_enabled
)
values (
  'ldnoobwv2',
  'LDNOOBW V2',
  'https://github.com/LDNOOBWV2/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words_V2',
  'CC0-1.0',
  'main',
  true
)
on conflict (source_key)
do update
set
  display_name =
    excluded.display_name,

  source_url =
    excluded.source_url,

  license_name =
    excluded.license_name,

  source_revision =
    excluded.source_revision,

  updated_at =
    now();


-- ============================================================================
-- LEXIQUE MONDIAL
--
-- action :
--
--   context
--     Terme potentiellement problématique.
--     Il ne bloque PAS tout seul.
--     Il renforce la décision de la modération contextuelle.
--
--   hard_block
--     Terme validé manuellement comme suffisamment grave et non ambigu.
--     Blocage direct côté serveur.
--
--   vulgarity
--     Terme grossier / vulgaire, conservé pour un futur filtre utilisateur,
--     mais pas utilisé comme interdiction de sécurité.
-- ============================================================================

create table if not exists public.moderation_global_lexicon (
  id bigint generated by default as identity
    primary key,

  source_key text not null
    references public.moderation_lexicon_sources(source_key)
    on delete cascade,

  language_code text not null,

  term text not null,

  normalized_term text not null,

  action text not null
    default 'context',

  active boolean not null
    default true,

  created_at timestamptz not null
    default now(),

  updated_at timestamptz not null
    default now(),

  constraint moderation_global_lexicon_action_check
    check (
      action in (
        'context',
        'hard_block',
        'vulgarity'
      )
    ),

  constraint moderation_global_lexicon_unique_term
    unique (
      source_key,
      language_code,
      normalized_term
    )
);


alter table public.moderation_global_lexicon
enable row level security;


-- Le téléphone n'a pas besoin de télécharger 50 000+ termes.
-- Toute la grosse liste reste côté serveur.
revoke all
on public.moderation_global_lexicon
from anon,
     authenticated;


-- Index B-tree : la fonction V2.2 cherche des candidats exacts normalisés,
-- au lieu de parcourir toute la table à chaque message.
create index if not exists
  idx_moderation_global_lexicon_normalized_active
on public.moderation_global_lexicon (
  normalized_term
)
where active = true;


create index if not exists
  idx_moderation_global_lexicon_action_active
on public.moderation_global_lexicon (
  action,
  normalized_term
)
where active = true;


create index if not exists
  idx_moderation_global_lexicon_language
on public.moderation_global_lexicon (
  language_code
);


-- ============================================================================
-- RPC DE MATCH RAPIDE
--
-- L'Edge Function envoie uniquement les mots / expressions possibles du
-- message. PostgreSQL fait alors des recherches exactes via l'index.
--
-- Pas d'accès client : service_role uniquement.
-- ============================================================================

create or replace function public.project_xp_match_global_lexicon(
  p_candidates text[]
)
returns table (
  term text,
  normalized_term text,
  language_code text,
  action text
)

language sql

stable

security definer

set search_path =
  public

as $$

  select
    l.term,
    l.normalized_term,
    l.language_code,
    l.action

  from
    public.moderation_global_lexicon as l

  where
    l.active = true

    and l.normalized_term = any(
      coalesce(
        p_candidates,
        array[]::text[]
      )
    )

  order by
    case l.action
      when 'hard_block' then 0
      when 'context' then 1
      else 2
    end,

    char_length(
      l.normalized_term
    ) desc

  limit 100;

$$;


revoke all
on function public.project_xp_match_global_lexicon(text[])
from public,
     anon,
     authenticated;


grant execute
on function public.project_xp_match_global_lexicon(text[])
to service_role;


-- ============================================================================
-- JOURNAL DE MODÉRATION
--
-- Créé ici afin que les logs V2.1/V2.2 fonctionnent AVANT le lockdown final.
-- Le texte brut du message n'y est pas copié.
-- ============================================================================

create table if not exists public.moderation_events (
  id bigint generated by default as identity
    primary key,

  user_id uuid
    references auth.users(id)
    on delete set null,

  surface text not null,

  decision text not null,

  categories text[] not null
    default '{}'::text[],

  content_sha256 text,

  created_at timestamptz not null
    default now()
);


alter table public.moderation_events
enable row level security;


revoke all
on public.moderation_events
from anon,
     authenticated;


-- ============================================================================
-- OUTIL MANUEL : PROMOUVOIR UN TERME EN HARD BLOCK
--
-- Exemple (à utiliser seulement depuis le SQL Editor admin) :
--
-- update public.moderation_global_lexicon
-- set action = 'hard_block',
--     updated_at = now()
-- where language_code = 'fr'
--   and normalized_term = '...';
--
-- ============================================================================


-- ============================================================================
-- FIN - FOUNDATION V2.2
-- ============================================================================
